apiVersion: v1
kind: Service
metadata:
  name: backend-direct
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30004
  type: NodePort
