apiVersion: v1
kind: Service
metadata:
  name: frontend-direct
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30003
  type: NodePort
